from importlib.metadata import PackageNotFoundError, version

from dicehub.api_keys import (
    ApiKey,
    ApiKeyStatus,
    ApiKeyValidityStatus,
    CreatedApiKey,
    NamespacePermission,
)
from dicehub.apps import (
    App,
    AppDetail,
    AppMemberTeam,
    AppMemberUser,
    AppOrderField,
    AppPage,
    AppRole,
    AppTeamMembership,
    AppTeamMembershipPage,
    AppType,
    AppUserMembership,
    AppUserMembershipPage,
    AppVisibility,
)
from dicehub.async_client import AsyncClient
from dicehub.auth import AuthContext, IdentityMode
from dicehub.client import Client
from dicehub.configs import (
    Config,
    ConfigContentArea,
    ConfigContentEntry,
    ConfigContentPage,
    ConfigContentType,
    ConfigPage,
    ConfigValueUpdate,
    GeometryImportRuns,
)
from dicehub.errors import (
    APIError,
    AuthenticationError,
    AuthenticationRequiredError,
    ConfigurationError,
    DiceHubError,
    GraphQLError,
    HTTPError,
    MutationOutcomeUnknownError,
    ProtocolError,
    RunFailedError,
    RunTimeoutError,
    SelectorResolutionError,
    TransportError,
)
from dicehub.groups import (
    Group,
    GroupDetail,
    GroupMemberTeam,
    GroupMemberUser,
    GroupOrderField,
    GroupPage,
    GroupRole,
    GroupTeamMembership,
    GroupTeamMembershipPage,
    GroupUserMembership,
    GroupUserMembershipPage,
    GroupVisibility,
    MembershipVisibility,
)
from dicehub.projects import (
    Project,
    ProjectDetail,
    ProjectMemberTeam,
    ProjectMemberUser,
    ProjectOrderField,
    ProjectPage,
    ProjectRole,
    ProjectTeamMembership,
    ProjectTeamMembershipPage,
    ProjectUserMembership,
    ProjectUserMembershipPage,
    ProjectVisibility,
    SortOrder,
)
from dicehub.resources import Resource, ResourcePage, ResourceType
from dicehub.runs import (
    MachinePrice,
    MachineType,
    Run,
    RunDetail,
    RunError,
    RunExecutionStatus,
    RunFlag,
    RunOrderField,
    RunPage,
    RunResultS3Credentials,
    RunState,
    RunStatus,
    RunType,
)
from dicehub.storage import DownloadReceipt, UploadReceipt
from dicehub.teams import Team
from dicehub.templates import (
    Template,
    TemplateOrderField,
    TemplatePage,
    TemplateTag,
    TemplateType,
)
from dicehub.users import MembershipCandidate, User

try:
    __version__ = version("dicehub-python")
except PackageNotFoundError:  # pragma: no cover - source tree without installation
    __version__ = "0+unknown"

__all__ = [
    "APIError",
    "ApiKey",
    "ApiKeyStatus",
    "ApiKeyValidityStatus",
    "App",
    "AppDetail",
    "AppMemberTeam",
    "AppMemberUser",
    "AppOrderField",
    "AppPage",
    "AppRole",
    "AppTeamMembership",
    "AppTeamMembershipPage",
    "AppType",
    "AppUserMembership",
    "AppUserMembershipPage",
    "AppVisibility",
    "AsyncClient",
    "AuthContext",
    "AuthenticationError",
    "AuthenticationRequiredError",
    "Client",
    "Config",
    "ConfigContentArea",
    "ConfigContentEntry",
    "ConfigContentPage",
    "ConfigContentType",
    "ConfigPage",
    "ConfigValueUpdate",
    "ConfigurationError",
    "CreatedApiKey",
    "DiceHubError",
    "DownloadReceipt",
    "GeometryImportRuns",
    "GraphQLError",
    "Group",
    "GroupDetail",
    "GroupMemberTeam",
    "GroupMemberUser",
    "GroupOrderField",
    "GroupPage",
    "GroupRole",
    "GroupTeamMembership",
    "GroupTeamMembershipPage",
    "GroupUserMembership",
    "GroupUserMembershipPage",
    "GroupVisibility",
    "HTTPError",
    "IdentityMode",
    "MachinePrice",
    "MachineType",
    "MembershipCandidate",
    "MembershipVisibility",
    "MutationOutcomeUnknownError",
    "NamespacePermission",
    "Project",
    "ProjectDetail",
    "ProjectMemberTeam",
    "ProjectMemberUser",
    "ProjectOrderField",
    "ProjectPage",
    "ProjectRole",
    "ProjectTeamMembership",
    "ProjectTeamMembershipPage",
    "ProjectUserMembership",
    "ProjectUserMembershipPage",
    "ProjectVisibility",
    "ProtocolError",
    "Resource",
    "ResourcePage",
    "ResourceType",
    "Run",
    "RunDetail",
    "RunError",
    "RunExecutionStatus",
    "RunFailedError",
    "RunFlag",
    "RunOrderField",
    "RunPage",
    "RunResultS3Credentials",
    "RunState",
    "RunStatus",
    "RunTimeoutError",
    "RunType",
    "SelectorResolutionError",
    "SortOrder",
    "Team",
    "Template",
    "TemplateOrderField",
    "TemplatePage",
    "TemplateTag",
    "TemplateType",
    "TransportError",
    "UploadReceipt",
    "User",
    "__version__",
]
